db:
  main:
    master:
      url: localhost
      port: 3306
      database: test1
      username: root
      password: password
    slave:
      url: localhost
      port: 3307
      database: test1
      username: root
      password: password

